#!/usr/bin/env python3
# This file is placed in the Public Domain.


"test"


import os
import sys


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()

popen("python3 -m pytest --show-capture=stdout --capture=sys")
